### ISSUE TITLE
Error console ec2 instance

### ISSUE THREAD

**Issue by FelipeGFalcao** [DNXLabs/terraform-aws-ecs#21]
Dear,
When executing the command, the instance does not include in the cluster and when accessing the instance logs it returns the following error:

`EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts (null)`

Could they help me?

**Comment by adenot** [comment]
@FelipeGFalcao that looks like a problem in your main EBS volume (the one with the OS). Can you provide more details?

**Comment by FelipeGFalcao** [comment]
Guys, I did the following, as I was still at the beginning of the project, I took some configurations from this repository.
https://github.com/DNXLabs/terraform-aws-network

With that I made small changes to the cluster configuration and it worked.
